---
title: "Make a map"
author: "Marc"
output:
  pdf_document:
    fig_caption: yes
    highlight: zenburn
    toc: yes
    toc_depth: '5'
  word_document:
    toc: yes
    toc_depth: '5'
  html_document:
    toc: true
    html-math-method: katex
    toc-depth: 3
    theme: cerulean
    df_print: paged
always_allow_html: yes
---

```{css, echo=FALSE}
/* Move code folding buttons to the left */
div.col-md-12 .pull-right {
  float: left !important
}
```


# Data wrangling

Basic settings, e.g., we read the basic packages and set the seed for reproducibility. The most relevant is the tidyverse work environment. See <https://www.tidyverse.org/> for more details.

```{r message=FALSE, warning=FALSE}
# load basic packages
#library(readxl)
library(tidyverse)
# for maps
library(rnaturalearth)
library(rnaturalearthdata)
library(maps)
```

# Figures

This is the code that generates a world map with Grambank data.
```{r message=FALSE, warning=FALSE}
# read Grambank data
data <- read.csv("data_raw/Grambank.csv")

# For entries that have precisely the same geographic coordinates as other entries, add 0.01 degrees 
#(on the order of hundreds of meters/the scale of towns or villages):
same_coords <- duplicated(data[, c("Latitude", "Longitude")]);
data$Latitude[ same_coords ] <- data$Latitude[ same_coords ] + 0.01
data$Longitude[ same_coords ] <- data$Longitude[ same_coords ] + 0.01

# duplicate the data to modify for map
l <- data %>%
  # remove points with no coordinates
  filter(!is.na(Longitude))

# set up the world map data
world <- ne_countries(scale = "medium", returnclass = "sf")

# function to change the coordinates to pacific-centred for visualization
shiftlong<-function(long) {
	if (long<(-20)){
		return(360+long)
		} else {return(long)
			}
	}

# apply the function
l$long<-sapply(l[,"Longitude"],shiftlong)
l$lat<-l[,"Latitude"]

# change the coordinates in world map to pacific centered
mapWorld <- map_data('world', wrap=c(-20,340), ylim=c(-60,100))
ggplot() +
  # set ocean color to blue
  theme(panel.background = element_rect(fill = "aliceblue"),
        # show panel border
        panel.border = element_rect(fill = NA)) +
  # can add xlim ylim below to zoom in on an area
  # e.g, xlim = c(60, 140), ylim = c(0,45)
  coord_equal(expand = FALSE) +
  geom_polygon(data = mapWorld, aes(x=long, y = lat, group = group) ,
               # set land color and coast color
               fill = "cornsilk", color = "grey") +
  # add language points
  geom_point(data = l, aes(x = long, y = lat,
                           color = GB522,
                           shape = GB521),
             alpha = 0.2) +
  #geom_density_2d(data = l, aes(x = long, y = lat))  +
  theme(legend.position = "top",
        axis.title=element_blank(),
        legend.title = element_blank(),
        #axis.text = element_blank(),
        legend.text=element_text(size=10)) +
  # overwrites the alpha for the legend
  guides(color = guide_legend(override.aes = list(alpha = 1))) +
  # manually set the colors
  scale_color_manual(values=c("darkgray","blue","red","black")) 
# save the map as png file
ggsave('World.png', width = 8, height = 4, dpi = 600)
```



